export const seedTasks = [
  { content_en: "Take a 10-min walk and buy yourself a fruit", content_cn: "出门散步十分钟并给自己买一份喜欢的水果", category: "wellness" },
  { content_en: "Send a message to a friend you haven't talked to", content_cn: "给一个很久没联系的朋友发一条消息", category: "social" },
  { content_en: "Spend 5 minutes decluttering your desk", content_cn: "花五分钟整理你的桌面只留下必需品", category: "mindful" },
  { content_en: "Do 10 squats and drink a glass of water", content_cn: "站起来做十个深蹲然后喝一杯水", category: "wellness" },
  { content_en: "Take a photo of something beautiful", content_cn: "用手机拍一张你觉得好看的东西", category: "creative" },
  { content_en: "Write down 3 things that made you happy today", content_cn: "写下三件今天让你开心的小事", category: "mindful" },
  { content_en: "Listen to a song you've never heard", content_cn: "听一首你从没听过的歌", category: "creative" },
  { content_en: "Close your eyes and take 5 deep breaths", content_cn: "闭上眼睛做五次深呼吸", category: "wellness" },
  { content_en: "Look out the window and observe the clouds", content_cn: "去窗边看看天空观察云的形状", category: "mindful" },
  { content_en: "Write an encouraging note to future you", content_cn: "给明天的自己写一句鼓励的话", category: "mindful" },
  { content_en: "Learn a fun fact and share it with someone", content_cn: "学一个冷知识然后讲给别人听", category: "social" },
  { content_en: "Draw whatever comes to mind right now", content_cn: "画一个你脑海里浮现的东西", category: "creative" },
  { content_en: "Walk around the block noticing new details", content_cn: "去楼下走一圈注意平时没注意的细节", category: "wellness" },
  { content_en: "Make a cup of tea and drink it slowly", content_cn: "给自己泡一杯茶安静地喝完", category: "mindful" },
  { content_en: "Clean up your phone gallery", content_cn: "整理手机相册删掉不需要的照片", category: "mindful" },
]
