// Quick seed script - run with: node scripts/run-seed.mjs
const SUPABASE_URL = 'https://iwndbljpyfbluttcnqvq.supabase.co'
const KEY = process.env.SK

if (!KEY) { console.error('Set SK env var'); process.exit(1) }

const tasks = [
  { content_cn: "喝一杯水", content_en: "Drink a glass of water", category: "wellness" },
  { content_cn: "散步10分钟", content_en: "Take a 10-minute walk", category: "wellness" },
  { content_cn: "做30分钟运动", content_en: "Do 30 minutes of exercise", category: "wellness" },
  { content_cn: "给自己做一顿健康的晚餐", content_en: "Cook yourself a healthy dinner", category: "wellness" },
  { content_cn: "给自己买一杯喜欢的饮料", content_en: "Buy yourself a favorite drink", category: "wellness" },
  { content_cn: "打扫掉桌面上不需要的东西", content_en: "Clear unnecessary items off your desk", category: "wellness" },
  { content_cn: "删掉10张相册里不需要的照片", content_en: "Delete 10 unwanted photos from your gallery", category: "wellness" },
  { content_cn: "早睡半小时", content_en: "Go to bed half an hour earlier", category: "wellness" },
  { content_cn: "拉伸身体5分钟", content_en: "Stretch your body for 5 minutes", category: "wellness" },
  { content_cn: "整理衣柜的一个角落", content_en: "Tidy up one corner of your closet", category: "wellness" },
  { content_cn: "吃一份水果", content_en: "Eat a serving of fruit", category: "wellness" },
  { content_cn: "换上干净的床单", content_en: "Change to clean bedsheets", category: "wellness" },
  { content_cn: "洗一个热水澡", content_en: "Take a hot shower", category: "wellness" },
  { content_cn: "整理钱包里的卡片和收据", content_en: "Organize the cards and receipts in your wallet", category: "wellness" },
  { content_cn: "删掉一个不用的app", content_en: "Delete an app you don't use", category: "wellness" },
  { content_cn: "把房间通风10分钟", content_en: "Air out your room for 10 minutes", category: "wellness" },
  { content_cn: "擦一下手机屏幕", content_en: "Wipe your phone screen clean", category: "wellness" },
  { content_cn: "整理一个抽屉", content_en: "Organize one drawer", category: "wellness" },
  { content_cn: "倒掉冰箱里过期的东西", content_en: "Throw out expired items from the fridge", category: "wellness" },
  { content_cn: "涂一次护手霜", content_en: "Apply hand cream", category: "wellness" },
  { content_cn: "慢慢喝完一杯茶", content_en: "Slowly finish a cup of tea", category: "wellness" },
  { content_cn: "站起来活动5分钟", content_en: "Stand up and move around for 5 minutes", category: "wellness" },
  { content_cn: "给植物浇水", content_en: "Water your plants", category: "wellness" },
  { content_cn: "提前准备好明天要穿的衣服", content_en: "Lay out tomorrow's clothes tonight", category: "wellness" },
  { content_cn: "对着镜子做一个最夸张的表情", content_en: "Make the most exaggerated face at a mirror", category: "wellness" },
  { content_cn: "做10个深蹲", content_en: "Do 10 squats", category: "wellness" },
  { content_cn: "整理电脑桌面", content_en: "Organize your computer desktop", category: "wellness" },
  { content_cn: "清空一个文件夹", content_en: "Empty out one folder", category: "wellness" },
  { content_cn: "关掉手机一小时", content_en: "Turn off your phone for an hour", category: "wellness" },
  { content_cn: "不带手机吃一顿饭", content_en: "Eat one meal without your phone", category: "wellness" },
  { content_cn: "准备一份健康的早餐", content_en: "Prepare a healthy breakfast", category: "wellness" },
  { content_cn: "在阳光下站5分钟", content_en: "Stand in the sunlight for 5 minutes", category: "wellness" },
  { content_cn: "学一只企鹅走五步", content_en: "Waddle like a penguin for 5 steps", category: "wellness" },
  { content_cn: "对自己比一个大大的耶", content_en: "Make a big peace sign at yourself", category: "wellness" },
  { content_cn: "取消一个不需要的订阅", content_en: "Cancel a subscription you don't need", category: "wellness" },
  { content_cn: "整理收件箱删掉50封邮件", content_en: "Clean out your inbox by deleting 50 emails", category: "wellness" },
  { content_cn: "把脏衣服放进洗衣篮", content_en: "Put dirty clothes in the laundry basket", category: "wellness" },
  { content_cn: "洗一次碗", content_en: "Wash the dishes", category: "wellness" },
  { content_cn: "把双手举到最高伸一个超大的懒腰", content_en: "Raise your arms as high as you can and stretch like a giant", category: "wellness" },
  { content_cn: "擦一次镜子", content_en: "Wipe a mirror clean", category: "wellness" },
  { content_cn: "对自己的倒影wink一下", content_en: "Wink at your own reflection", category: "wellness" },
  { content_cn: "给自己泡一杯热饮", content_en: "Brew yourself a warm drink", category: "wellness" },
  { content_cn: "吃一颗维生素", content_en: "Take a vitamin", category: "wellness" },
  { content_cn: "做5分钟眼保健操", content_en: "Do 5 minutes of eye exercises", category: "wellness" },
  { content_cn: "离开屏幕看远处30秒", content_en: "Look away from screens at something far for 30 seconds", category: "wellness" },
  { content_cn: "假装自己是一只猫慢慢伸个懒腰", content_en: "Pretend you're a cat and slowly stretch", category: "wellness" },
  { content_cn: "慢慢吃完一顿饭不看屏幕", content_en: "Eat one meal slowly without any screens", category: "wellness" },
  { content_cn: "洗一次头发", content_en: "Wash your hair", category: "wellness" },
  { content_cn: "修剪指甲", content_en: "Trim your nails", category: "wellness" },
  { content_cn: "整理床铺", content_en: "Make your bed", category: "wellness" },
  { content_cn: "把书桌上的水杯洗干净", content_en: "Wash the cups on your desk", category: "wellness" },
  { content_cn: "多走1000步", content_en: "Walk 1000 extra steps", category: "wellness" },
  { content_cn: "用最慢的速度眨眼三次", content_en: "Blink three times in extreme slow motion", category: "wellness" },
  { content_cn: "吃一份蔬菜", content_en: "Eat a serving of vegetables", category: "wellness" },
  { content_cn: "整理一下书架", content_en: "Tidy up a bookshelf", category: "wellness" },
  { content_cn: "对空气挥挥拳出三个空气拳", content_en: "Throw three punches at the empty air", category: "wellness" },
  { content_cn: "对着自己的脚趾大喊\"闪亮的脚趾\"", content_en: "Shout \"shiny toes!\" at your own toes", category: "wellness" },
  { content_cn: "学一只霸王龙把手缩在胸前走五步", content_en: "Walk 5 steps like a T-Rex with tiny arms", category: "wellness" },
  { content_cn: "把手机壁纸换成喜欢的图片", content_en: "Change your phone wallpaper to a picture you love", category: "wellness" },
  { content_cn: "打扫一下浴室", content_en: "Clean the bathroom", category: "wellness" },
  { content_cn: "对自己说一句\"今天的我也不错\"", content_en: "Say to yourself \"I'm doing alright today\"", category: "wellness" },
  { content_cn: "静止不动5秒不许笑", content_en: "Freeze completely still for 5 seconds without laughing", category: "wellness" },
  { content_cn: "把过期的药品扔掉", content_en: "Throw away expired medicine", category: "wellness" },
  { content_cn: "给自己冲一杯咖啡", content_en: "Make yourself a cup of coffee", category: "wellness" },
  { content_cn: "吃饭前认真洗手", content_en: "Wash your hands properly before eating", category: "wellness" },
  { content_cn: "出门晒15分钟太阳", content_en: "Spend 15 minutes outside in the sun", category: "wellness" },
  { content_cn: "整理冰箱里的食物", content_en: "Organize the food in your fridge", category: "wellness" },
  { content_cn: "把不要的衣服放进捐赠袋", content_en: "Put unwanted clothes in a donation bag", category: "wellness" },
  { content_cn: "踮脚走十步", content_en: "Walk 10 steps on your tiptoes", category: "wellness" },
  { content_cn: "对自己竖一个大拇指", content_en: "Give yourself a thumbs up", category: "wellness" },
  { content_cn: "原地小跳5下", content_en: "Do 5 small jumps in place", category: "wellness" },
  { content_cn: "摇头晃脑哼一段没有调的歌", content_en: "Hum a tuneless melody while swaying your head", category: "wellness" },
  { content_cn: "给左手和右手分别取一个名字", content_en: "Give your left and right hand each a name", category: "wellness" },
  { content_cn: "让自己午睡20分钟", content_en: "Give yourself a 20-minute nap", category: "wellness" },
  { content_cn: "做5分钟瑜伽", content_en: "Do 5 minutes of yoga", category: "wellness" },
  { content_cn: "按摩一下肩膀", content_en: "Massage your shoulders", category: "wellness" },
  { content_cn: "对自己的影子打个招呼", content_en: "Say hi to your own shadow", category: "wellness" },
  { content_cn: "旋转一圈再继续做事", content_en: "Spin around once before continuing what you were doing", category: "wellness" },
  { content_cn: "深呼吸5次", content_en: "Take 5 deep breaths", category: "mindful" },
  { content_cn: "记录今天值得开心的三件事", content_en: "Write down 3 things that made you happy today", category: "mindful" },
  { content_cn: "闭上眼睛听1分钟周围的声音", content_en: "Close your eyes and listen to your surroundings for 1 minute", category: "mindful" },
  { content_cn: "写下一个最近的感受", content_en: "Write down one feeling you've had recently", category: "mindful" },
  { content_cn: "静坐5分钟", content_en: "Sit quietly for 5 minutes", category: "mindful" },
  { content_cn: "给身边一个物品偷偷起一个名字", content_en: "Secretly give a name to an object near you", category: "mindful" },
  { content_cn: "想一个让你笑的回忆", content_en: "Recall a memory that makes you smile", category: "mindful" },
  { content_cn: "想象自己有一种超能力并想想会怎么用", content_en: "Imagine you have a superpower and think about how you'd use it", category: "mindful" },
  { content_cn: "给自己写一句鼓励的话", content_en: "Write yourself one encouraging sentence", category: "mindful" },
  { content_cn: "闭眼回想昨天最美好的一刻", content_en: "Close your eyes and recall the best moment of yesterday", category: "mindful" },
  { content_cn: "写下三个你最喜欢自己的地方", content_en: "Write down 3 things you love about yourself", category: "mindful" },
  { content_cn: "给自己取一个秘密代号", content_en: "Give yourself a secret codename", category: "mindful" },
  { content_cn: "对空气挥挥手打个招呼", content_en: "Wave hello to the empty air", category: "mindful" },
  { content_cn: "留5分钟什么都不做", content_en: "Spend 5 minutes doing absolutely nothing", category: "mindful" },
  { content_cn: "想一件你完成过的事并为自己骄傲", content_en: "Think of something you accomplished and feel proud", category: "mindful" },
  { content_cn: "写下明天最期待的一件小事", content_en: "Write down one small thing you look forward to tomorrow", category: "mindful" },
  { content_cn: "在心里和过去的自己说一句话", content_en: "Say one thing in your heart to your past self", category: "mindful" },
  { content_cn: "写下今天学到的一件事", content_en: "Write down one thing you learned today", category: "mindful" },
  { content_cn: "闭眼感受呼吸2分钟", content_en: "Close your eyes and feel your breath for 2 minutes", category: "mindful" },
  { content_cn: "想象一个让你放松的地方", content_en: "Picture a place that makes you feel calm", category: "mindful" },
  { content_cn: "入睡前想象自己是一只伸展的海星", content_en: "Before sleep, imagine you're a stretched-out starfish", category: "mindful" },
  { content_cn: "列出三个你信任的人", content_en: "List 3 people you trust", category: "mindful" },
  { content_cn: "写下你今年最想完成的一件事", content_en: "Write down one thing you most want to accomplish this year", category: "mindful" },
  { content_cn: "给未来的自己写一句话", content_en: "Write one sentence to your future self", category: "mindful" },
  { content_cn: "回想一个对你重要的人并默默感谢他", content_en: "Think of someone important and silently thank them", category: "mindful" },
  { content_cn: "写下一个你今天做得不错的小决定", content_en: "Write down one good small decision you made today", category: "mindful" },
  { content_cn: "想象自己是一朵慢慢飘的云", content_en: "Imagine you're a cloud drifting slowly", category: "mindful" },
  { content_cn: "静静观察一片树叶或一朵花", content_en: "Quietly observe a leaf or a flower", category: "mindful" },
  { content_cn: "数一数自己呼吸了多少次", content_en: "Count how many breaths you take", category: "mindful" },
  { content_cn: "写下最近让你感动的一个瞬间", content_en: "Write down a moment that touched you recently", category: "mindful" },
  { content_cn: "闭眼感受双脚踩在地面的感觉", content_en: "Close your eyes and feel your feet on the ground", category: "mindful" },
  { content_cn: "写下一句最近常想的话", content_en: "Write down a phrase that's been on your mind", category: "mindful" },
  { content_cn: "列出三件你今年完成的事", content_en: "List 3 things you accomplished this year", category: "mindful" },
  { content_cn: "想象自己住在一座漂浮的小岛上", content_en: "Imagine you live on a floating little island", category: "mindful" },
  { content_cn: "写下一件让你今天舒服的事", content_en: "Write down something that made today comfortable", category: "mindful" },
  { content_cn: "慢慢吃一口食物并感受味道", content_en: "Slowly take one bite of food and savor the flavor", category: "mindful" },
  { content_cn: "听完一首歌不做别的事", content_en: "Listen to a full song without doing anything else", category: "mindful" },
  { content_cn: "假装自己是一棵大树站30秒", content_en: "Stand still like a tree for 30 seconds", category: "mindful" },
  { content_cn: "写下三个让你今天感到平静的瞬间", content_en: "Write down 3 moments that made you feel calm today", category: "mindful" },
  { content_cn: "想一个你最近变得更好的小变化", content_en: "Think of one small way you've grown recently", category: "mindful" },
  { content_cn: "感受一下自己手心的温度", content_en: "Feel the warmth of your own palms", category: "mindful" },
  { content_cn: "慢慢洗手并感受水流", content_en: "Wash your hands slowly and feel the water", category: "mindful" },
  { content_cn: "想象自己掉进了一碗布丁里", content_en: "Imagine yourself falling into a giant bowl of pudding", category: "mindful" },
  { content_cn: "对自己的左脚说一句早上好", content_en: "Say good morning to your left foot", category: "mindful" },
  { content_cn: "在心里默念一句让自己安心的话", content_en: "Silently say a calming phrase to yourself", category: "mindful" },
  { content_cn: "写下你今天最想感谢的人", content_en: "Write down the person you most want to thank today", category: "mindful" },
  { content_cn: "静静看窗外1分钟", content_en: "Look out the window quietly for 1 minute", category: "mindful" },
  { content_cn: "闭眼想象明天会是美好的一天", content_en: "Close your eyes and imagine tomorrow being a great day", category: "mindful" },
  { content_cn: "写一句让你安心的话贴在桌前", content_en: "Write a comforting sentence and stick it on your desk", category: "mindful" },
  { content_cn: "写下三个你想要的小目标", content_en: "Write down 3 small goals you want to reach", category: "mindful" },
  { content_cn: "在心里给今天打一个分数", content_en: "Give today a score in your head", category: "mindful" },
  { content_cn: "告诉自己今天做得好的地方", content_en: "Tell yourself what you did well today", category: "mindful" },
  { content_cn: "闭眼听一首慢歌", content_en: "Close your eyes and listen to a slow song", category: "mindful" },
  { content_cn: "慢慢从1数到100", content_en: "Slowly count from 1 to 100", category: "mindful" },
  { content_cn: "假装自己是一个呼吸缓慢的乌龟", content_en: "Pretend you're a slow-breathing turtle", category: "mindful" },
  { content_cn: "静静站着30秒不做任何事", content_en: "Stand still for 30 seconds doing nothing", category: "mindful" },
  { content_cn: "想一件你期待的远期未来的事", content_en: "Think of something you're looking forward to in the distant future", category: "mindful" },
  { content_cn: "写下最近让你最有动力的一件事", content_en: "Write down something that has been motivating you lately", category: "mindful" },
  { content_cn: "想象自己一年后的样子", content_en: "Picture yourself one year from now", category: "mindful" },
  { content_cn: "写下今天让你笑出声的一刻", content_en: "Write down a moment that made you laugh out loud today", category: "mindful" },
  { content_cn: "跟现在出现在你脑海的人发一条消息", content_en: "Send a message to whoever just popped into your head", category: "social" },
  { content_cn: "和朋友或伴侣分享一件和对方有关的小事", content_en: "Share with a friend or partner a small thing related to them", category: "social" },
  { content_cn: "给家人打一个电话", content_en: "Call a family member", category: "social" },
  { content_cn: "给一个很久没联系的朋友发消息", content_en: "Message a friend you haven't talked to in a while", category: "social" },
  { content_cn: "真诚地夸奖一个人", content_en: "Sincerely compliment someone", category: "social" },
  { content_cn: "对今天遇到的人说谢谢", content_en: "Say thank you to someone you met today", category: "social" },
  { content_cn: "给朋友推荐一首你最近喜欢的歌", content_en: "Recommend a song you've been loving to a friend", category: "social" },
  { content_cn: "给一个朋友发一句\"今天怎么样\"", content_en: "Send a friend \"how's your day going\"", category: "social" },
  { content_cn: "给朋友发一张今天看到的好看的照片", content_en: "Send a friend a nice photo from today", category: "social" },
  { content_cn: "对店员说谢谢和再见", content_en: "Say thanks and goodbye to a shop clerk", category: "social" },
  { content_cn: "给家人发一句晚安", content_en: "Send your family a goodnight message", category: "social" },
  { content_cn: "给朋友发一条没有目的的消息", content_en: "Send a friend a message with no purpose", category: "social" },
  { content_cn: "回复一条积压很久没回的消息", content_en: "Reply to a message you've been putting off", category: "social" },
  { content_cn: "给朋友推荐一本书或一部电影", content_en: "Recommend a book or movie to a friend", category: "social" },
  { content_cn: "给妈妈或爸爸发一条消息", content_en: "Send a message to your mom or dad", category: "social" },
  { content_cn: "给朋友讲一件小时候的趣事", content_en: "Tell a friend a funny childhood memory", category: "social" },
  { content_cn: "给一个朋友发个语音消息", content_en: "Send a voice message to a friend", category: "social" },
  { content_cn: "给家人发一张今天的自拍", content_en: "Send your family a selfie from today", category: "social" },
  { content_cn: "真诚地问朋友最近怎么样", content_en: "Sincerely ask a friend how they're doing", category: "social" },
  { content_cn: "给一个朋友发一个可爱的动物图片", content_en: "Send a friend a cute animal photo", category: "social" },
  { content_cn: "给一个朋友讲今天最有意思的事", content_en: "Tell a friend the most interesting thing from your day", category: "social" },
  { content_cn: "给朋友发一个表情包", content_en: "Send a friend a meme", category: "social" },
  { content_cn: "给朋友讲一个今天发生的小笑话", content_en: "Tell a friend a small funny thing from today", category: "social" },
  { content_cn: "给朋友发一张你窗外的景色", content_en: "Send a friend a photo of the view from your window", category: "social" },
  { content_cn: "给朋友发一张你今天觉得好看的东西", content_en: "Send a friend a photo of something you found beautiful today", category: "social" },
  { content_cn: "和朋友聊聊最近在想的事", content_en: "Chat with a friend about something on your mind", category: "social" },
  { content_cn: "写下三个你想感谢的朋友", content_en: "Write down 3 friends you want to thank", category: "social" },
  { content_cn: "给朋友发一句\"谢谢你存在\"", content_en: "Send a friend \"thanks for existing\"", category: "social" },
  { content_cn: "给朋友发一句想你了", content_en: "Send a friend \"I miss you\"", category: "social" },
  { content_cn: "给朋友的朋友圈点个赞", content_en: "Like a friend's social media post", category: "social" },
  { content_cn: "给一个朋友发一首你单曲循环的歌", content_en: "Send a friend a song you've had on repeat", category: "social" },
  { content_cn: "给一个朋友发\"想到你了\"", content_en: "Tell a friend \"I just thought of you\"", category: "social" },
  { content_cn: "回想一个朋友对你的好并默默感谢他", content_en: "Recall a friend's kindness and silently thank them", category: "social" },
  { content_cn: "和一个朋友分享今天的心情", content_en: "Share your mood today with a friend", category: "social" },
  { content_cn: "给朋友发一段最近读到喜欢的句子", content_en: "Send a friend a line you've recently liked from something you read", category: "social" },
  { content_cn: "给朋友发一张窗外天空的照片", content_en: "Send a friend a photo of the sky outside your window", category: "social" },
  { content_cn: "和朋友聊一段你最近的小烦恼", content_en: "Tell a friend about a small worry you've had", category: "social" },
  { content_cn: "对一个家人发一条暖心的消息", content_en: "Send a warm message to a family member", category: "social" },
  { content_cn: "问爸妈最近过得怎么样", content_en: "Ask your parents how they've been", category: "social" },
  { content_cn: "给一个家人发一张今天的照片", content_en: "Send a family member a photo from today", category: "social" },
  { content_cn: "告诉一个朋友TA对你的意义", content_en: "Tell a friend what they mean to you", category: "social" },
  { content_cn: "真诚地为别人庆祝一件小事", content_en: "Sincerely celebrate a small win for someone else", category: "social" },
  { content_cn: "给朋友讲一个最近读到的有意思的事", content_en: "Tell a friend something interesting you read recently", category: "social" },
  { content_cn: "问朋友想不想一起做一件事", content_en: "Ask a friend if they'd want to do something together", category: "social" },
  { content_cn: "在群里说一句问候的话", content_en: "Say hi in a group chat", category: "social" },
  { content_cn: "给朋友写一段长一点的消息", content_en: "Write a longer message to a friend", category: "social" },
  { content_cn: "和一个朋友约下次见面", content_en: "Plan a next meet-up with a friend", category: "social" },
  { content_cn: "给一个朋友发\"谢谢你最近\"", content_en: "Tell a friend \"thank you for being there recently\"", category: "social" },
  { content_cn: "对今天遇到的服务人员说一句感谢", content_en: "Thank a service worker you encountered today", category: "social" },
  { content_cn: "给一直支持你的人写一句感谢", content_en: "Write a thank-you note to someone who supports you", category: "social" },
  { content_cn: "给朋友讲一件最近让你感动的事", content_en: "Tell a friend about something that touched you recently", category: "social" },
  { content_cn: "找一个朋友聊聊你的烦恼", content_en: "Talk to a friend about something on your mind", category: "social" },
  { content_cn: "问一个朋友最近在追什么剧", content_en: "Ask a friend what they've been watching", category: "social" },
  { content_cn: "在群聊里分享一件好事", content_en: "Share good news in a group chat", category: "social" },
  { content_cn: "给朋友讲一个今天遇到的小温暖", content_en: "Tell a friend about a small warm moment from today", category: "social" },
  { content_cn: "给朋友发一句早安或晚安", content_en: "Send a friend a \"good morning\" or \"good night\"", category: "social" },
  { content_cn: "回想一个老朋友并发一条消息", content_en: "Think of an old friend and send them a message", category: "social" },
  { content_cn: "给一个朋友发一张你今天的鞋子", content_en: "Send a friend a photo of the shoes you wore today", category: "social" },
  { content_cn: "拍下今天的云", content_en: "Take a photo of today's clouds", category: "creative" },
  { content_cn: "用手机拍一张你觉得好看的东西", content_en: "Take a phone photo of something you find beautiful", category: "creative" },
  { content_cn: "听一首没听过的歌", content_en: "Listen to a song you've never heard before", category: "creative" },
  { content_cn: "画一个简单的涂鸦", content_en: "Doodle something simple", category: "creative" },
  { content_cn: "在纸上随便写一段话", content_en: "Write a random paragraph on paper", category: "creative" },
  { content_cn: "拍一张今天的天空", content_en: "Take a photo of today's sky", category: "creative" },
  { content_cn: "拍一张光影好看的瞬间", content_en: "Capture a moment with beautiful light and shadow", category: "creative" },
  { content_cn: "把今天最喜欢的一件事画下来", content_en: "Draw your favorite moment from today", category: "creative" },
  { content_cn: "给今天起一个名字", content_en: "Give today a name", category: "creative" },
  { content_cn: "用三个词形容今天", content_en: "Describe today in 3 words", category: "creative" },
  { content_cn: "写下一个突然想到的小点子", content_en: "Write down a small idea that just came to you", category: "creative" },
  { content_cn: "拍一张你脚下地面的照片", content_en: "Take a photo of the ground at your feet", category: "creative" },
  { content_cn: "听一个新的播客", content_en: "Listen to a new podcast", category: "creative" },
  { content_cn: "看一部从没看过的短片", content_en: "Watch a short film you've never seen", category: "creative" },
  { content_cn: "把书桌按你喜欢的方式重新摆一遍", content_en: "Rearrange your desk the way you like", category: "creative" },
  { content_cn: "写下三个生活里的小灵感", content_en: "Write down 3 small inspirations from daily life", category: "creative" },
  { content_cn: "拍一张你最喜欢的角落", content_en: "Take a photo of your favorite corner", category: "creative" },
  { content_cn: "用手机录一段一分钟的环境声音", content_en: "Record a 1-minute audio of your surroundings", category: "creative" },
  { content_cn: "写一首四行的小诗", content_en: "Write a 4-line poem", category: "creative" },
  { content_cn: "给某个普通物品想一个新用途", content_en: "Think of a new use for an everyday object", category: "creative" },
  { content_cn: "重新整理一下手机相册", content_en: "Reorganize your phone photo albums", category: "creative" },
  { content_cn: "给手机里的相册起一个新名字", content_en: "Rename a photo album on your phone", category: "creative" },
  { content_cn: "听一首小时候喜欢的歌", content_en: "Listen to a song you loved as a kid", category: "creative" },
  { content_cn: "写下一个梦境的片段", content_en: "Write down a piece of a dream", category: "creative" },
  { content_cn: "用手机拍一张影子的照片", content_en: "Take a phone photo of a shadow", category: "creative" },
  { content_cn: "写一段100字以内的故事", content_en: "Write a story under 100 words", category: "creative" },
  { content_cn: "用一种新方式走熟悉的路", content_en: "Take a familiar route in a new way", category: "creative" },
  { content_cn: "试一道没做过的菜", content_en: "Try cooking a new dish", category: "creative" },
  { content_cn: "把今天最想说的话写下来", content_en: "Write down what you most want to say today", category: "creative" },
  { content_cn: "用一支彩色笔画一个图案", content_en: "Draw a pattern with a colored pen", category: "creative" },
  { content_cn: "给最喜欢的物品拍一张照", content_en: "Take a photo of your favorite object", category: "creative" },
  { content_cn: "拍一张今天的早餐或晚餐", content_en: "Photograph your breakfast or dinner today", category: "creative" },
  { content_cn: "找一首今天的主题曲", content_en: "Find a \"theme song\" for today", category: "creative" },
  { content_cn: "写下今天看到的一个有意思的细节", content_en: "Write down one interesting detail you noticed today", category: "creative" },
  { content_cn: "试着用非惯用手写自己的名字", content_en: "Try writing your name with your non-dominant hand", category: "creative" },
  { content_cn: "听一个完全陌生的音乐流派", content_en: "Listen to a completely unfamiliar music genre", category: "creative" },
  { content_cn: "在窗边坐10分钟看外面", content_en: "Sit by the window for 10 minutes and watch outside", category: "creative" },
  { content_cn: "给自己拍一张今天的自拍", content_en: "Take a selfie of yourself today", category: "creative" },
  { content_cn: "给一张老照片写一句话", content_en: "Write a caption for an old photo", category: "creative" },
  { content_cn: "把一首喜欢的歌词抄下来", content_en: "Copy down lyrics from a song you love", category: "creative" },
  { content_cn: "看一段5分钟的纪录片片段", content_en: "Watch a 5-minute documentary clip", category: "creative" },
  { content_cn: "找一个有趣的视频看", content_en: "Find an interesting video to watch", category: "creative" },
  { content_cn: "把今天遇到最美的颜色记下来", content_en: "Write down the most beautiful color you saw today", category: "creative" },
  { content_cn: "用手机拍下今天穿的鞋子", content_en: "Take a phone photo of the shoes you wore today", category: "creative" },
  { content_cn: "给今天的心情画一个表情", content_en: "Draw an emoji for today's mood", category: "creative" },
  { content_cn: "用手机拍一张身边的小动物或植物", content_en: "Photograph a small animal or plant nearby", category: "creative" },
  { content_cn: "重新摆一下房间里的一样东西", content_en: "Move something in your room to a new spot", category: "creative" },
  { content_cn: "用今天的颜色拼一张mood board", content_en: "Make a mood board with today's colors", category: "creative" },
  { content_cn: "写一句没有理由的话送给自己", content_en: "Write yourself a sentence for no reason", category: "creative" },
  { content_cn: "了解一个新领域的知识并分享给朋友", content_en: "Learn something in a new field and share it with a friend", category: "learning" },
  { content_cn: "学习一句非母语的语言", content_en: "Learn one phrase in a non-native language", category: "learning" },
  { content_cn: "查一个你今天好奇的问题", content_en: "Look up a question you were curious about today", category: "learning" },
  { content_cn: "读一篇1000字左右的文章", content_en: "Read an article around 1000 words", category: "learning" },
  { content_cn: "学一个新词", content_en: "Learn a new word", category: "learning" },
  { content_cn: "看一段TED演讲", content_en: "Watch a TED talk", category: "learning" },
  { content_cn: "读一页你正在看的书", content_en: "Read one page of your current book", category: "learning" },
  { content_cn: "学一个新的快捷键", content_en: "Learn a new keyboard shortcut", category: "learning" },
  { content_cn: "查一个不认识的成语或谚语", content_en: "Look up an idiom or proverb you don't know", category: "learning" },
  { content_cn: "了解一种你没听过的食物", content_en: "Learn about a food you've never heard of", category: "learning" },
  { content_cn: "看一段历史小故事", content_en: "Read a short historical story", category: "learning" },
  { content_cn: "找一个你想学的技能并写下第一步", content_en: "Find a skill you want to learn and write down the first step", category: "learning" },
  { content_cn: "看一段关于宇宙的小知识", content_en: "Read a short fact about the universe", category: "learning" },
  { content_cn: "了解一个你感兴趣的城市", content_en: "Learn about a city that interests you", category: "learning" },
  { content_cn: "查一首你最近常听的歌的歌词意思", content_en: "Look up the meaning of lyrics in a song you've been playing", category: "learning" },
  { content_cn: "查一个你常用却不懂含义的词", content_en: "Look up a word you use often but don't fully understand", category: "learning" },
  { content_cn: "了解一种你没接触过的文化", content_en: "Learn about a culture you haven't encountered", category: "learning" },
  { content_cn: "看一个5分钟的科普视频", content_en: "Watch a 5-minute educational video", category: "learning" },
  { content_cn: "阅读一篇新闻并思考自己的看法", content_en: "Read a news article and form your own opinion", category: "learning" },
  { content_cn: "学习识别一种新的植物或鸟", content_en: "Learn to identify a new plant or bird", category: "learning" },
  { content_cn: "了解一种你感兴趣的职业", content_en: "Learn about a career that interests you", category: "learning" },
  { content_cn: "找一本你想读的书并加入收藏", content_en: "Find a book you want to read and save it", category: "learning" },
  { content_cn: "学一个新的科学小知识", content_en: "Learn a new science fact", category: "learning" },
  { content_cn: "看一个关于艺术的小知识", content_en: "Read a small fact about art", category: "learning" },
  { content_cn: "学一个新的烹饪技巧", content_en: "Learn a new cooking technique", category: "learning" },
  { content_cn: "了解一首你常听的歌的故事", content_en: "Learn the story behind a song you often listen to", category: "learning" },
  { content_cn: "学一个新的英文单词", content_en: "Learn a new English word", category: "learning" },
  { content_cn: "了解一个app的一个新功能", content_en: "Learn one new feature of an app", category: "learning" },
  { content_cn: "看一段历史人物的小传记", content_en: "Read a short biography of a historical figure", category: "learning" },
  { content_cn: "找一个你想了解的话题查三篇资料", content_en: "Pick a topic and read 3 sources on it", category: "learning" },
  { content_cn: "学一个新的呼吸法", content_en: "Learn a new breathing technique", category: "learning" },
  { content_cn: "了解一种新动物", content_en: "Learn about a new animal", category: "learning" },
  { content_cn: "看一段关于地理的有趣事实", content_en: "Read an interesting geography fact", category: "learning" },
  { content_cn: "查一个你一直好奇的冷知识", content_en: "Look up a piece of trivia you've been wondering about", category: "learning" },
  { content_cn: "了解一种新的咖啡或茶", content_en: "Learn about a new type of coffee or tea", category: "learning" },
  { content_cn: "看一段电影幕后花絮", content_en: "Watch a behind-the-scenes clip from a movie", category: "learning" },
  { content_cn: "找一个免费在线课程的第一节看", content_en: "Watch the first lesson of a free online course", category: "learning" },
  { content_cn: "查一个你今天看到却不认识的字或符号", content_en: "Look up a character or symbol you saw today but didn't know", category: "learning" },
  { content_cn: "找一个你想学的乐器了解一下", content_en: "Look up an instrument you'd like to learn", category: "learning" },
  { content_cn: "查一个你最近常听到的新词", content_en: "Look up a new word you've been hearing recently", category: "learning" },
  { content_cn: "了解一个本地的历史故事", content_en: "Learn a local historical story", category: "learning" },
  { content_cn: "看一个关于心理学的小知识", content_en: "Read a small fact about psychology", category: "learning" },
  { content_cn: "学习一个新的写作技巧", content_en: "Learn a new writing technique", category: "learning" },
  { content_cn: "了解一种你没尝过的水果", content_en: "Learn about a fruit you've never tried", category: "learning" },
  { content_cn: "看一段关于设计的小视频", content_en: "Watch a short video about design", category: "learning" },
  { content_cn: "学一个新的表格技巧", content_en: "Learn a new spreadsheet trick", category: "learning" },
  { content_cn: "了解一个你常用品牌的故事", content_en: "Learn the story of a brand you often use", category: "learning" },
  { content_cn: "找一个你关心的话题听一段播客", content_en: "Listen to a podcast on a topic you care about", category: "learning" },
  { content_cn: "学一个新的拍照构图技巧", content_en: "Learn a new photo composition tip", category: "learning" },
  { content_cn: "把今天学到的事情用一句话总结", content_en: "Summarize what you learned today in one sentence", category: "learning" },
]

async function seed() {
  console.log(`Inserting ${tasks.length} tasks...`)
  const bs = 50
  let ok = 0
  for (let i = 0; i < tasks.length; i += bs) {
    const batch = tasks.slice(i, i + bs)
    const res = await fetch(`${SUPABASE_URL}/rest/v1/public_tasks`, {
      method: 'POST',
      headers: {
        'apikey': KEY,
        'Authorization': `Bearer ${KEY}`,
        'Content-Type': 'application/json',
        'Prefer': 'return=minimal',
      },
      body: JSON.stringify(batch),
    })
    if (!res.ok) {
      console.error(`Batch error:`, await res.text())
    } else {
      ok += batch.length
      console.log(`  ${ok}/${tasks.length}`)
    }
  }
  console.log(`\nDone! ${ok} tasks inserted.`)
}

seed().catch(console.error)
